"""Run: python3 -m unittest discover -s tools/git"""

from __future__ import annotations

import unittest

from check_message import check_message, find_attribution


class CheckMessageTest(unittest.TestCase):
    def test_accepts_one_line_conventional_subjects(self) -> None:
        for message in (
            "feat: add drum draw",
            "fix: keep the judge flag after reconnect\n",
            "docs: update CLAUDE.md",
            "chore: bump livekit to 1.13.7",
            "# Please enter the commit message\ntest: cover recall\n\n# comment\n",
            "refactor: split the publisher\n"
            "# ------------------------ >8 ------------------------\ndiff --git a b\n",
        ):
            with self.subTest(message=message):
                self.assertIsNone(check_message(message))

    def test_rejects_malformed_subjects(self) -> None:
        for message in (
            "",
            "# only a comment\n",
            "add drum draw",
            "feature: add drum draw",
            "feat(api): add drum draw",
            "feat:add drum draw",
            "feat: Add drum draw",
            "feat: add drum draw.",
            "feat: " + "a" * 95,
            "feat: добавить барабан",
            "feat: add drum draw\n\nWith a body.",
        ):
            with self.subTest(message=message):
                self.assertIsNotNone(check_message(message))

    def test_rejects_attribution_even_in_service_messages(self) -> None:
        for message in (
            "feat: add drum\n\nCo-Authored-By: Someone <noreply@anthropic.com>",
            "Merge branch 'main'\n\nco-authored-by: x",
            "feat: add drum via claude",
            "feat: add drum 🤖",
        ):
            with self.subTest(message=message):
                reason = check_message(message)
                self.assertIsNotNone(reason)
                self.assertIn("attribution", reason or "")

    def test_merge_subjects_are_allowed_only_for_commits(self) -> None:
        self.assertIsNone(check_message("Merge branch 'main' into chore/ci"))
        self.assertIsNotNone(check_message("Merge branch 'main'", allow_merge=False))
        self.assertIsNone(check_message('Revert "feat: add drum"', allow_merge=False))

    def test_attribution_patterns(self) -> None:
        for text in (
            "Co-Authored-By: x",
            "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
            "generated by Claude",
            "written using Anthropic models",
            "see claude.ai",
        ):
            with self.subTest(text=text):
                self.assertIsNotNone(find_attribution(text))
        for text in (
            "update CLAUDE.md",
            "types generated by openapi-typescript",
            ".claude/hooks/git-guard.py",
        ):
            with self.subTest(text=text):
                self.assertIsNone(find_attribution(text))


if __name__ == "__main__":
    unittest.main()
